/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laa;

import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author Filipe Santana
 */
public class Janelainicial extends javax.swing.JFrame {

    /**
     * Creates new form Janelainicial
     */
    public Janelainicial() {
        initComponents();
        this.ordenacao = new Ordenacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoOrdenacaoRadio = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        AbaBusca = new javax.swing.JPanel();
        ConjuntoNumLabel = new javax.swing.JLabel();
        NumBuscaLabel = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        AbaComplexidade = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        AbaOrdenacao = new javax.swing.JPanel();
        ConjNumOrdLabel = new javax.swing.JLabel();
        ResulOrdLabel = new javax.swing.JLabel();
        VetorOrdText = new javax.swing.JTextField();
        InsertionOrdButton = new javax.swing.JRadioButton();
        BubbleOrdButton = new javax.swing.JRadioButton();
        SelectionOrdButton = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        RespostaOrdenacao = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ConjuntoNumLabel.setText("Conjunto de números");

        NumBuscaLabel.setText("Número a ser buscado");

        jButton3.setText("Busca");

        javax.swing.GroupLayout AbaBuscaLayout = new javax.swing.GroupLayout(AbaBusca);
        AbaBusca.setLayout(AbaBuscaLayout);
        AbaBuscaLayout.setHorizontalGroup(
            AbaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaBuscaLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(AbaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaBuscaLayout.createSequentialGroup()
                        .addComponent(ConjuntoNumLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AbaBuscaLayout.createSequentialGroup()
                        .addComponent(NumBuscaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(AbaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        AbaBuscaLayout.setVerticalGroup(
            AbaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaBuscaLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(AbaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConjuntoNumLabel)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(AbaBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NumBuscaLabel)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton3)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Busca", AbaBusca);

        jLabel4.setText("N:");

        jLabel5.setText("Complexidade:");

        jLabel6.setText("Processamento:");

        jButton2.setText("Verificar");

        jLabel3.setText("[Resultado]");

        javax.swing.GroupLayout AbaComplexidadeLayout = new javax.swing.GroupLayout(AbaComplexidade);
        AbaComplexidade.setLayout(AbaComplexidadeLayout);
        AbaComplexidadeLayout.setHorizontalGroup(
            AbaComplexidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaComplexidadeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(AbaComplexidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(AbaComplexidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaComplexidadeLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addGroup(AbaComplexidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                        .addComponent(jTextField2)
                        .addComponent(jTextField3)))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        AbaComplexidadeLayout.setVerticalGroup(
            AbaComplexidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaComplexidadeLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(AbaComplexidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AbaComplexidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AbaComplexidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(AbaComplexidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel3))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Complexidade", AbaComplexidade);

        ConjNumOrdLabel.setText("Conjunto de números");

        VetorOrdText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VetorOrdTextActionPerformed(evt);
            }
        });

        GrupoOrdenacaoRadio.add(InsertionOrdButton);
        InsertionOrdButton.setText("Insertion");

        GrupoOrdenacaoRadio.add(BubbleOrdButton);
        BubbleOrdButton.setText("Bubble");

        GrupoOrdenacaoRadio.add(SelectionOrdButton);
        SelectionOrdButton.setText("Selection");

        GrupoOrdenacaoRadio.add(jRadioButton4);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });

        RespostaOrdenacao.setText("Resultado,");

        jButton4.setText("Ordenar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AbaOrdenacaoLayout = new javax.swing.GroupLayout(AbaOrdenacao);
        AbaOrdenacao.setLayout(AbaOrdenacaoLayout);
        AbaOrdenacaoLayout.setHorizontalGroup(
            AbaOrdenacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaOrdenacaoLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(AbaOrdenacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(RespostaOrdenacao)
                    .addComponent(ConjNumOrdLabel))
                .addGap(18, 18, 18)
                .addGroup(AbaOrdenacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InsertionOrdButton)
                    .addComponent(ResulOrdLabel)
                    .addComponent(VetorOrdText, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(AbaOrdenacaoLayout.createSequentialGroup()
                        .addGroup(AbaOrdenacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SelectionOrdButton)
                            .addComponent(BubbleOrdButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jRadioButton4))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        AbaOrdenacaoLayout.setVerticalGroup(
            AbaOrdenacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AbaOrdenacaoLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(AbaOrdenacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConjNumOrdLabel)
                    .addComponent(VetorOrdText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ResulOrdLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InsertionOrdButton)
                .addGroup(AbaOrdenacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AbaOrdenacaoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BubbleOrdButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectionOrdButton))
                    .addGroup(AbaOrdenacaoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addComponent(RespostaOrdenacao)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ordenação", AbaOrdenacao);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String vetorTexto = this.VetorOrdText.getText().trim();
        if (vetorTexto.isEmpty()) {
            JOptionPane.showMessageDialog(null, "O campo do vetor está vazio");
        }
        String botaoSelecionado = this.RetornaBotaoOrdenacaoSelecionado(GrupoOrdenacaoRadio);
        if (botaoSelecionado == null) {
            JOptionPane.showMessageDialog(null, "Não foi selecionado nenhum tipo de ordenação");
        }
        int[] vetorNumeros = ConverteListaStringToInt(vetorTexto.split(","));
        long inicio = System.nanoTime();
        switch (botaoSelecionado.toLowerCase()) {
            case "insertion" :                
                break;
            case "bubble":
                break;
            case "selection":
                this.ordenacao.SelectionSort(vetorNumeros);
                break;
            case "heap":
                break;
            default:
                break;
        }
        long tempoTotal = System.nanoTime()- inicio;
        this.RespostaOrdenacao.setText("");
        this.RespostaOrdenacao.setText(this.ordenacao.printaVetor(vetorNumeros)+",Tempo de execução: " + tempoTotal + "(nanosegundos)" );        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void VetorOrdTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VetorOrdTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VetorOrdTextActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    public String RetornaBotaoOrdenacaoSelecionado(ButtonGroup GrupodeBotoes) {
        for (Enumeration<AbstractButton> buttons = GrupodeBotoes.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    private int[] ConverteListaStringToInt(String[] vetorTexto) {
        List<Integer> listaDeNumeros = new ArrayList<>();
        for (String elemento : vetorTexto) {
            listaDeNumeros.add(Integer.parseInt(elemento));
        }
        int[] arrayDeNumeros = new int[listaDeNumeros.size()];
        for (int i = 0; i < listaDeNumeros.size(); i++) {
            arrayDeNumeros[i] = listaDeNumeros.get(i);
        }
        return arrayDeNumeros;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Janelainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Janelainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Janelainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Janelainicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janelainicial().setVisible(true);
            }
        });
    }

    private Ordenacao ordenacao;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AbaBusca;
    private javax.swing.JPanel AbaComplexidade;
    private javax.swing.JPanel AbaOrdenacao;
    private javax.swing.JRadioButton BubbleOrdButton;
    private javax.swing.JLabel ConjNumOrdLabel;
    private javax.swing.JLabel ConjuntoNumLabel;
    private javax.swing.ButtonGroup GrupoOrdenacaoRadio;
    private javax.swing.JRadioButton InsertionOrdButton;
    private javax.swing.JLabel NumBuscaLabel;
    private javax.swing.JLabel RespostaOrdenacao;
    private javax.swing.JLabel ResulOrdLabel;
    private javax.swing.JRadioButton SelectionOrdButton;
    private javax.swing.JTextField VetorOrdText;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
